name: XRmine Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Secret API
        run: echo ${{ secrets.XAMAN_APIKEY }}

      - name: Secret Wallet
        run: echo ${{ secrets.DROP_XRMINE }}

      - name: Enviroment Secret API
        run: echo ${{ secrets.XAMAN_APIKEY_NEW }}

      - name: Enviroment Secret Wallet
        run: echo ${{ secrets.DROP_WALLET_XRMINE }}
